// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAumlAtc6tzDyz79qdQV2OUDAlymt5uDmA',
    appId: '1:954460473121:web:1453edc506d54177a3a060',
    messagingSenderId: '954460473121',
    projectId: 'expense-tracker-flutter-8af48',
    authDomain: 'expense-tracker-flutter-8af48.firebaseapp.com',
    storageBucket: 'expense-tracker-flutter-8af48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3YOIIbwcAIrM59veVZPPneGH_7VopW0w',
    appId: '1:954460473121:android:0250fc9aa62122bba3a060',
    messagingSenderId: '954460473121',
    projectId: 'expense-tracker-flutter-8af48',
    storageBucket: 'expense-tracker-flutter-8af48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAewN95V7Al9xeQ19G-OOAuWTwlHzrCEk',
    appId: '1:954460473121:ios:20ee57c5513cab41a3a060',
    messagingSenderId: '954460473121',
    projectId: 'expense-tracker-flutter-8af48',
    storageBucket: 'expense-tracker-flutter-8af48.appspot.com',
    iosClientId:
        '954460473121-v7347hmk48kbvtbuff2tnclji375mlru.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerFlutter',
  );
}
